services :
    resulter_jdbc_db :
        image : 'postgres:latest'
        ports :
            - '5432:5432'
        environment :
            - 'POSTGRES_USER=resulter'
            - 'POSTGRES_DB=resulter'
            - 'POSTGRES_PASSWORD=resulter'
