[_]
schema-version = "0.2"

[build]
[[build.env]]
name = "BP_JVM_VERSION"
value = "21"

[[launch.env]]
name = "LANG"
value = "C.UTF-8"

[[launch.env]]
name = "LC_ALL"
value = "C.UTF-8"

[metadata]
name = "resulter-backend"
version = "4.9.3"
