INSERT INTO ORGANISATION_ORGANISATION (ORGANISATION_ID, PARENT_ORGANISATION_ID)
VALUES ((SELECT id FROM ORGANISATION WHERE SHORT_NAME = 'LV_BE'),
        (SELECT id FROM ORGANISATION WHERE SHORT_NAME = 'NOR'));
INSERT INTO ORGANISATION_ORGANISATION (ORGANISATION_ID, PARENT_ORGANISATION_ID)
VALUES ((SELECT id FROM ORGANISATION WHERE SHORT_NAME = 'LV_BB'),
        (SELECT id FROM ORGANISATION WHERE SHORT_NAME = 'NOR'));
INSERT INTO ORGANISATION_ORGANISATION (ORGANISATION_ID, PARENT_ORGANISATION_ID)
VALUES ((SELECT id FROM ORGANISATION WHERE SHORT_NAME = 'LV_MV'),
        (SELECT id FROM ORGANISATION WHERE SHORT_NAME = 'NOR'));
